### PR TITLE
Refactor ansible

### PR DESCRIPTION
**Pull request by stbenjam**
Work in progress, now that we don't need the hacks this makes the boxes built by ansible

### CODE REVIEW

**Comment by stbenjam** [comment]
@beav This gets a clean install just by doing `vagrant up centos7-katello-nightly-p4`, only thing is you need Vagrant 1.8.0 or higher (comes with Fedora 24 at least) to get the host_vars options

**Comment by beav** [comment]
@stbenjam very cool, I will update to F24 on my hypervisor and then try it out.

**Comment by beav** [comment]
@stbenjam this works for me. It still has the WIP label but it seems OK, is anything else needed before merging to the main PR?

**Comment by stbenjam** [comment]
Oh no merge away

**Pull request merged**
